export default {
  chatInfo: async (bot, update, args) => bot.getChatInfo(update, args),
  ping: async (bot, update, args) => bot.ping(update, args),
  toss: async (bot, update, args) => bot.toss(update, args),
  balance: async (bot, update, args) => bot.balance(update, args),
  epoch: async (bot, update, args) => bot.epoch(update, args),
  kanye: async (bot, update, args) => bot.kanye(update),
  bored: async (bot, update, args) => bot.bored(update, args),
  joke: async (bot, update, args) => bot.joke(update, args),
  doge: async (bot, update, args) => bot.doge(update, args),
  roll: async (bot, update, args) => bot.roll(update, args),
  recursion: async (bot, update, args) => bot.recursion(update, args),
  numbers: async (bot, update, args) => bot.numbers(update, args),
  average: async (bot, update, args) => bot.average(update, args),
  _get: async (bot, update, args) => bot._get(update, args),
  _set: async (bot, update, args) => bot._set(update, args),
  commandList: async (bot, update, args) => bot.commandList(update, args),
};
