export default {
  chatInfo: async (bot, update, args) => bot.getChatInfo(update),
  ping: async (bot, update, args) => bot.ping(update),
  toss: async (bot, update, args) => bot.toss(update),
  balance: async (bot, update, args) => bot.balance(update, args),
  epoch: async (bot, update, args) => bot.epoch(update),
  kanye: async (bot, update, args) => bot.kanye(update),
  bored: async (bot, update, args) => bot.bored(update),
  joke: async (bot, update, args) => bot.joke(update),
  doge: async (bot, update, args) => bot.doge(update),
  roll: async (bot, update, args) => bot.roll(update, args),
  recursion: async (bot, update, args) => bot.recursion(update),
  numbers: async (bot, update, args) => bot.numbers(update, args),
  average: async (bot, update, args) => bot.average(update),
  _get: async (bot, update, args) => bot._get(update, args),
  _set: async (bot, update, args) => bot._set(update, args),
  duckduckgo: async (bot, update, args) => bot.duckduckgo(update, args),
  commandList: async (bot, update, args) => bot.commandList(update),
};
